version: '3'
services:
  data_storage:
    image: data:storage
    environment:
      - BUCKET_AWS_ACCESS_KEY_ID=${BUCKET_AWS_ACCESS_KEY_ID}
      - BUCKET_AWS_SECRET_ACCESS_KEY=${BUCKET_AWS_SECRET_ACCESS_KEY}
      - BUCKET_NAME=${BUCKET_NAME}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - REGION=${REGION}
      - ROLE=${ROLE}
      - STAGE=${STAGE}
      - IS_DEV=false
      - AWS_ENDPOINT=${AWS_ENDPOINT}
      - MAIN_NETWORK=${MAIN_NETWORK}
      - PRIV_NETWORK=${PRIV_NETWORK}
      - DB_ENDPOINT=${DB_ENDPOINT}
      - TB_UPLOAD=${TB_UPLOAD}
      - PG_USER=${PG_USER}
      - PG_HOST=${PG_HOST}
      - PG_DATABASE=${PG_DATABASE}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_PORT=${PG_PORT}
      - DATA_FACTORY_ACCOUNT=${DATA_FACTORY_ACCOUNT}
      - DATA_FACTORY_ADDRESS=${DATA_FACTORY_ADDRESS}
      - DATA_PROVIDER_ADDRESS=${DATA_PROVIDER_ADDRESS}
    command: bash -c "nodemon --legacy-watch handler.js"